version: '3.8'

services:

  lambda:
    container_name: lambda-empty-function
    image: lambda-empty-function
    build:
      context: ./LambdaEmptyFunction
      dockerfile: ./Dockerfile
    ports:
      - "9000:8080"